# GENERATED by bootstrap-backend.ps1 - do not edit by hand.
#
# No access key, no connection string, no secret. Authentication is your Entra
# identity via use_azuread_auth. This file is safe to commit.
terraform {
  backend "azurerm" {
    resource_group_name  = "rg-terraform-state"
    storage_account_name = "sttfstatebhanu7391"
    container_name       = "tfstate"
    key                  = "foundation.tfstate"
    use_azuread_auth     = true
  }
}